import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';

import favIcon from '@/assets/images/favicon.ico';
import { MoveToTopButton } from '@/components/ui/buttons';
import { ScrollArea } from '@/components/ui/scroll-area';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: {
    template: '%s | Books Maison',
    default: 'Books Maison',
  },
  description: 'Generated by create next app',
  icons: favIcon.src,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <ScrollArea className="relative h-dvh w-full">
          {children}
          <MoveToTopButton />
        </ScrollArea>
        <Toaster richColors closeButton position="top-right" duration={3000} />
        <SpeedInsights />
      </body>
    </html>
  );
}
